default: &default
  MAIL_SERVER: smtp.gmail.com
  MAIL_SERVER_PORT: 587
  MAIL_DOMAIN: gmail.com
  MAIL_USERNAME: wongwf82biz
  MAIL_PASSWORD: qwerty82

development:
  <<: *default

production:
  <<: *default